### ISSUE TITLE
Examples code

### ISSUE THREAD

**Issue by rishabmahesh** [sekizlipenguen/react-native-popup-confirm-toast#13]
Hello,

Great library here. Can you please upload the code for the example gifs? It would be super helpful!

**Comment by sekizlipenguen** [comment]
Thank you :)

Sample screenshots already attached :)

I am attaching a short video.

https://user-images.githubusercontent.com/36849861/209683723-c9d345b7-cbca-4ed3-8ec2-a45b31f5b35d.mov

**Comment by rishabmahesh** [comment]
Hello @sekizlipenguen ,

Looks like I wasn't clear with my question. Is it possible for you to upload the code for the app that we can see in the README? The app which you are showing in the example with all the different popups and stuff. 

If I can see the code for that, it would serve as a great reference for my own implementation
