### ISSUE TITLE
undefined is not an object (evaluating 'this.popupInstance.start')  

### ISSUE THREAD

**Issue by KatuGT** [sekizlipenguen/react-native-popup-confirm-toast#14]
Hello! I am having a problen, I can´t make it work
This is my code

 ```
const handleDelete = (id) => {
    Popup.show({
      type: 'success',
      title: 'Dikkat!',
      textBody: 'Mutlak özgürlük, kendi başına hiçbir anlam ifade etmez. ',
      buttonText: 'Tamam',
      callback: () => Popup.hide()
    })
    const trabajosFiltrados = userInfo?.workExperience.filter((work) => {
      return work._id !== id;
    });

    // dispatch(
    //   editPersonalInfo(
    //     {
    //       workExperience: [...trabajosFiltrados],
    //     },
    //     userInfo?.token
    //   )
    // )
    //   .then(() => dispatch(Cambiador(!activador)))
    //   .catch((error) => console.log(error));
  };
```

I was just testing but I get this error
 **ERROR  TypeError: undefined is not an object (evaluating 'this.popupInstance.start')**

**Comment by KatuGT** [comment]
I have the imports
import { Root, Popup } from 'react-native-popup-confirm-toast'

**Comment by sekizlipenguen** [comment]
why did you turn it off?

It is necessary to apply the "Provider" operation inside the app.js file.

import {Root as PopupRoot} from 'react-native-popup-confirm-toast';

<PopupRoot>
....
</PopupRoot>


![Screen Shot 2023-02-28 at 22 42 02](https://user-images.githubusercontent.com/36849861/221961390-fba6a8a5-03f5-4751-82ed-5f687c7e46d2.png)

**Comment by KatuGT** [comment]
Because stupid me didn´t use the <Root> component, that was the problem 
I should close the "close with comment" button to explain

**Comment by sekizlipenguen** [comment]
> Because stupid me didn´t use the component, that was the problem I should close the "close with comment" button to explain

hey no problem! Don't forget to give a star if you like it :)
