### ISSUE TITLE
Buggy when resizing web version

### ISSUE THREAD

**Issue by KxmischesDomi** [sekizlipenguen/react-native-popup-confirm-toast#18]
When resizing the web version and make it bigger than when loading the app there is a weird gradient on the screen.

![image](https://user-images.githubusercontent.com/67184131/235967529-2fcc9b4b-5c72-42f9-a391-20a87f756683.png)

**Comment by sekizlipenguen** [comment]
I hope this version will fix the problem.

https://www.npmjs.com/package/react-native-popup-confirm-toast
version: 2.3.2

**Comment by sekizlipenguen** [comment]
> When resizing the web version and make it bigger than when loading the app there is a weird gradient on the screen.
> 
> ![image](https://user-images.githubusercontent.com/67184131/235967529-2fcc9b4b-5c72-42f9-a391-20a87f756683.png)

did this solve your problem?

**Comment by sekizlipenguen** [comment]
Closed due to long time no response.

**Comment by KxmischesDomi** [comment]
Sadly the issue still exists after updating the package :/
