### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by hirbod** [sekizlipenguen/react-native-popup-confirm-toast#2]
Nice,

awesome library. I really like it and it works great on "react-native-web" and expo as well.
Some thoughts:

- Missing Types
- Does not respond to width changes. Maybe add support with `useWindowDimensions();`
- Does not take the react-navigation header height into account when setting y translate. `useHeaderHeight()` might be useful.
- Support for hooks with a global provider wrapper
- Typescript

Beside of these its working great and you should add "web" support on the README, because it works nice.

**Comment by sekizlipenguen** [comment]
Hi,
I continue to move forward, taking into account your suggestions here.
thank you for your support
