### ISSUE TITLE
Getting "Property 'props' doesn't exist" error when use "bodyComponent" property

### ISSUE THREAD

**Issue by mburakucar** [sekizlipenguen/react-native-popup-confirm-toast#21]
I am using the example in the "[Example Custom Body Component](https://github.com/sekizlipenguen/react-native-popup-confirm-toast#example-custom-body-component)" section in the document and I am getting the error "Property 'props' doesn't exist".

**Comment by sekizlipenguen** [comment]
Hi,

Actually, "props" here means props in your own hook system or this.props if you are using the class system. You can remove "props" from here, it was just an example.


<Root>
    <View>
        <TouchableOpacity
            onPress={() => {
                const popup = Popup;
                popup.show({
                    type: 'confirm',
                    textBody: 'Hesabınızın silinme işlemini onaylamak için şifrenizi giriniz.',
                    bodyComponent: (bodyProps) => bodyComponent({bodyProps,popup}),
                    confirmText: 'Cancel',
                    iconEnabled: false,
                    buttonEnabled: false,
                });
            }}
        >
            <Text>Open Popup Confirm Message</Text>
        </TouchableOpacity>
    </View>
</Root>
