### ISSUE TITLE
Weird bug when putting <PopupRootProvider></PopupRootProvider> into app.js

### ISSUE THREAD

**Issue by Loris83** [sekizlipenguen/react-native-popup-confirm-toast#23]
Hello, first thank for your work, it is amazing.
I have a weird issue when using it unfortunately. When using it, I can slide down my app, as if there was something after my screen. Take a look : 

![image](https://github.com/sekizlipenguen/react-native-popup-confirm-toast/assets/104614971/ea678268-5714-42e6-85ad-ceda058d5f53)
![image](https://github.com/sekizlipenguen/react-native-popup-confirm-toast/assets/104614971/3fbe07c0-6bb7-4ff7-980b-ef1997a9e1d7)
(I can keep scrolling until i don't see the page anymore)
It only happens when i put <PopupRootProvider></PopupRootProvider> into my app.js.
![image](https://github.com/sekizlipenguen/react-native-popup-confirm-toast/assets/104614971/7e939b82-3337-4e68-a2d2-817393de5367)
Do you have an idea how to fix that ?
Many thanks in advance.

**Comment by sekizlipenguen** [comment]
![Screenshot 2024-07-16 at 09 13 27](https://github.com/user-attachments/assets/6850e130-8d45-4221-836c-4715c1ed9dba)

Hello,

It's been a while, I hope you have found a solution. However, from what I can see, you have wrapped your component with SafeAreaProvider. When using NavigationContainer, I know that this isn't necessary and it might be the reason you're facing the issue. It would be a good idea to try removing SafeAreaProvider and see if that resolves the problem.

**Comment by anniewey** [comment]
@sekizlipenguen i tried to wrap safearea inside root but still facing same issue. We need the safearea for certain usage in the app. Any idea?

```
import { Root } from 'react-native-popup-confirm-toast';

<Root>
      <SafeAreaProvider>
        <StatusBar
          barStyle='dark-content'
          backgroundColor={Colour.White}
          translucent={true}
        />
        <TourGuideProvider
          preventOutsideInteraction
         ...
        >
          <AuthContext setLoggedInState={setLoggedIn}>
            <NavigationContainer ref={navigationRef}>
              <RootStackNavigator isLoggedIn={isLoggedIn} />
            </NavigationContainer>
          </AuthContext>
        </TourGuideProvider>
      </SafeAreaProvider>
    </Root>
```

"react-native-popup-confirm-toast": "^2.2.7",
