### ISSUE TITLE
Timing continues when using multiple toast notifications

### ISSUE THREAD

**Issue by gijsjager** [sekizlipenguen/react-native-popup-confirm-toast#24]
I am facing issue that when I want to show a user a toast message multiple times in a short row, the timing won't reset and can't be adjusted. This is causing that the later added message won't be visible for a very long time. 

It would be nice to reset the timing or to stack the toast message when calling the toast.show() method multiple times in a row. 

I am using 
`"react-native-popup-confirm-toast": "^2.3.5",`

**Comment by sekizlipenguen** [comment]
Hello,

Thank you for suggesting the feature to continue development.

I have an update related to this development. Do you have a chance to try it out manually by making the changes?

https://github.com/sekizlipenguen/react-native-popup-confirm-toast/commit/c497b38c9070a5cd14f6ca8983c0aa271ed6a9bb

**Comment by sekizlipenguen** [comment]
To test the new version, you can install it as follows.
I'm waiting for their return.

npm install "eightlipenguin/react-native-popup-confirm-toast#c497b38c9070a5cd14f6ca8983c0aa271ed6a9bb"

**Comment by gijsjager** [comment]
@sekizlipenguen this seems to work as I would expect! 🎉

**Comment by sekizlipenguen** [comment]
This request has been completed with version 2.3.6.

https://www.npmjs.com/package/react-native-popup-confirm-toast/v/2.3.6
