### ISSUE TITLE
No callback for cancel

### ISSUE THREAD

**Issue by Standin-Alone** [sekizlipenguen/react-native-popup-confirm-toast#3]

**Comment by sekizlipenguen** [comment]
Any chance to elaborate?

**Comment by Standin-Alone** [comment]
your callback function is for confirm button only. i can't get the cancel button callback

**Comment by sekizlipenguen** [comment]
Will this function be sufficient? I will bring a new update.

Uploading Screen Recording 2
![ezgif-1-29d8589951](https://user-images.githubusercontent.com/36849861/154430613-e5e3dd4d-017a-4ae1-9fc6-24ef35884cc2.gif)

**Comment by sekizlipenguen** [comment]
https://www.npmjs.com/package/react-native-popup-confirm-toast

Your request was brought with version 2.0.6.
