### ISSUE TITLE
Code Question 

### ISSUE THREAD

**Issue by goxr3plus** [sekizlipenguen/react-native-popup-confirm-toast#5]
Why inside the code 

![image](https://user-images.githubusercontent.com/20374208/157333996-50a9a7f8-de15-4447-aef7-a9e307f0c70f.png)

useNativeDriver is false instead of true , you have a special reason for that ?

**Comment by sekizlipenguen** [comment]
Some react native versions had performance issues. I will make the "useNativeDriver" parameter changeable :)

**Comment by sekizlipenguen** [comment]
New Version: 2.0.7

https://www.npmjs.com/package/react-native-popup-confirm-toast

![Screen Shot 2022-03-09 at 12 44 54](https://user-images.githubusercontent.com/36849861/157415765-e2269ae2-1fd2-48c1-aa2e-3185acaa50da.png)
