### ISSUE TITLE
Why we need to use root component?

### ISSUE THREAD

**Issue by jv640** [sekizlipenguen/react-native-popup-confirm-toast#7]
I have code where i have 2 tabs on same screen and when i'm using popup there then the popup is showing on the 2nd screen instead of 1st.

I tried to find out what was the cause and figured out the Root component was the issue if I don't use root in any of tabs then I was getting this error `TypeError: undefined is not an object (evaluating 'this.popupInstance.start')` and if i was using root on only 1st tab then popup was shown on 1st and if i was using root on both then pop was shown in second whether i was triggering it from 1st tab or 2nd tab

**Comment by sekizlipenguen** [comment]
We need the "root" structure so that we can go on top of all screens. You should apply the "root" structure in index.js

I've never checked for multiple "popup" builds at once, I'll be planning a development for this soon.

I think the problem is related to "z-index"

**Comment by sekizlipenguen** [comment]
Hi,

This version may be the solution for you: https://www.npmjs.com/package/react-native-popup-confirm-toast/v/2.2.2
