### ISSUE TITLE
modifying header background color not exposed

### ISSUE THREAD

**Issue by chidimez** [sekizlipenguen/react-native-popup-confirm-toast#8]
I looked through the docs for popup and realized there is no way to modify the header style sheet. am using a dark theme and i have a white background behind my icons due to this. am currently using a modified fork to workaround this.  The relevant codes are:

Popup.js:
```
{
                        iconEnabled && (
                            <>
                                <View style={styles.Header}/>
                               ...
                            </>
                        )
                    }
```

Style Sheet:
```
Header: {
       ...
       backgroundColor: '#fff',
    },
```

**Comment by sekizlipenguen** [comment]
I received this request, I will add it to the development soon

**Comment by sekizlipenguen** [comment]
hi,
this version may be the solution for you: https://www.npmjs.com/package/react-native-popup-confirm-toast/v/2.2.2

iconHeaderStyle={{bla,bla,bla}}

**Comment by chidimez** [comment]
Thanks!
